### ISSUE TITLE
swapping with unequal allocators calls unreachable

### ISSUE THREAD

**Issue by Ukilele** [jbcoe/value_types#202]
Following code shows a test that erroneously fails.
```c++
TEST(Indirect, AllocatorSwapIssue) {
  auto* resourceA = std::pmr::new_delete_resource();
  unsigned char buffer[1024];
  std::pmr::monotonic_buffer_resource resourceB(buffer, 1024);

  std::pmr::polymorphic_allocator allocA(resourceA);
  std::pmr::polymorphic_allocator allocB(&resourceB);

  xyz::indirect<int, std::pmr::polymorphic_allocator<int>> iA(
      std::allocator_arg, allocA, 10);
  xyz::indirect<int, std::pmr::polymorphic_allocator<int>> iB(
      std::allocator_arg, allocB, 220);

  iA.swap(iB);
  EXPECT_EQ(*iA, 220);
  EXPECT_EQ(*iB, 10);
}
```
We have two indirects `iA` and `iB` using a `std::pmr::polymorphic_allocator<int>` where both allocators are constructed from a different resource, such that `alloc_ == other.alloc_` returns `false`. When calling `iA.swap(iB)` then we currently hit the call to `unreachable` at https://github.com/jbcoe/value_types/blob/main/indirect.h#L224 . The same issue applies to `polymorphic`.

**Comment by Ukilele** [comment]
In the draft.md at https://github.com/jbcoe/value_types/blob/main/DRAFT.md#modelled-types-for-indirect it says:

> Like `vector`, `indirect` marks member and non-member `swap` as noexcept and requires allocators to be equal.

`vector` marks `swap` not as noexcept. It marks it as noexcept(allocator_traits<Allocator>::propagate_on_container_swap::value || allocator_traits<Allocator>::is_always_equal::value). And it also does not require allocators to be equal, right?

**Comment by jbcoe** [comment]
This behaves as intended. 

https://en.cppreference.com/w/cpp/container/vector/swap

Has: "If [std::allocator_traits](http://en.cppreference.com/w/cpp/memory/allocator_traits)<allocator_type>::propagate_on_container_swap::value is true, then the allocators are exchanged using an unqualified call to non-member swap. Otherwise, they are not swapped (and if get_allocator() != other.get_allocator(), the behavior is undefined)."

As a container of one element, we model vector.

**Comment by Ukilele** [comment]
Oh I didn't know that. I'm sorry for the noise! Then everything works as expected and I just have to brush up my knowledge about allocators ;)

**Comment by jbcoe** [comment]
Thanks for raising this.

**Comment by jbcoe** [comment]
We could add a test to see that this does result in unreachable being called.

**Comment by lewissbaker** [comment]
The current wording according to here: http://eel.is/c++draft/vector#capacity-12 doesn't seem to indicate that it's UB to swap two containers with unequal allocators.

Is there some other intro section that defines this, perhaps?

**Comment by lewissbaker** [comment]
Ok, I found this wording: https://eel.is/c++draft/container.requirements#container.reqmts-65

So, yes, I agree that the current wording of making it undefined behaviour to swap an object with unequal allocators is consistent with other containers.

However, I wonder whether that constraint was because they wanted the `swap()` operation to be constant-time.
For the purposes of the `indirect` and `polymorphic`, you could implement `swap()` to swap the elements and it would still be constant-time (although the container requirements do specify that it shouldn't be implemented in terms of swapping the elements). Containers of size one could be argued to both be O(1) and O(n)...

**Comment by jbcoe** [comment]
I don't think we can swap elements between different allocators, they'd risk being destroyed by things that did not compare equal with their creator.
