### ISSUE TITLE
[QUESTION] Removal of std::optional specialization from the P3019 proposal

### ISSUE THREAD

**Issue by AbhinavK00** [jbcoe/value_types#241]
In the github issues for tracking wg21 issues, one of the poll at the Kona meetings was about the removal of std::optional specialization (along with other things) which had strong consensus in favor. This is just a question, but I'm curious what led to this decision, more about what implications it would have on the unobservable null state. The authors were in favour of this decision so there must be reasons for this decision. I'm sorry if this repo is not for these type of questions.

Also, the [[no_unique_address]] can be used to leverage empty member optimization when the allocator used is stateless, is that a enhancement worthy of this feature?

**Comment by jbcoe** [comment]
Thanks for your question. This is the right place to ask.

Implementers felt that requring `std::optional<indirect<T>>` and `std::optional<polymorphic<T>>` to be the same size as `indirect<T>` and `polymorphic<T>` was unnecessary as it's something they were free to do and likely to do anyway.

The idea behind requiring the optimisation is that the valueless state can be exploited to represent an empty optional rather than requiring optional to track its engaged state. That would mean that an engaged-but-valueless optional indirect was not representable, but as valueless is intended to be unobservable, that's fine.

Removing the wording from the paper does not remove the possibility of this optimisation, just the requirement to do it.

I'm not sure what you mean by "Also, the [[no_unique_address]] can be used to leverage empty member optimization when the allocator used is stateless, is that a enhancement worthy of this feature?" We use this optimisation in our C++20 implementation. Perhaps you can clarify?

**Comment by AbhinavK00** [comment]
> We use this optimisation in our C++20 implementation.

I was not aware, but that was my recommendation. I said that because the paper didn't mention it. Is it because, like the std::optional specialization, it's something that implementers were likely to do so it was not worth requiring it?

Thanks for the reply! Really appreciate it.
